name: DeathSwap
main: deathSwap.DeathSwap
version: 1.0
api-version: 1.15
commands:
    startsession:
        description: Generates a new Death Swap session.
    joinsession:
        description: Join the existing Death Swap session.